deploy-win:
  image: electronuserland/electron-builder:wine
  environment: production-win
  cache:
    paths:
      - node_modules/
  before_script:
    - cd source/www
    - node -v
    - npm -v
    - yarn --version
    - yarn
  artifacts:
    paths:
      - $CI_PROJECT_DIR/source/www/dist/*.*
  script:
    - apt-get install -y git
    - sed -i -e 's/https:\/\/gitlab.com\/civx/ssh+git:\/\/git@gitlab.com:civx/g' package.json
    - CI=false yarn build && CI=false yarn dist
  only:
    - master
  tags:
    - docker