deploy-mac:
  image: electronuserland/electron-builder:wine
  stage: build
  environment: production-mac
  before_script:
    - cd source/www
    - node -v
    - npm -v
    - yarn --version
    - yarn
  script:
    - sed -i -e 's/https:\/\/gitlab.com\/civx/ssh+git:\/\/git@gitlab.com:civx/g' package.json
    - CI=false yarn build && CI=false yarn electron-pack:mac
  only:
    - master
  tags:
    - mac