before_script:
  - cd source/www
  - apt-get update
  - apt-get install build-essential libssl-dev
  - curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
  - nvm install 8.11.0
  - nvm use 8.11.0
  - npm -v
  - npm i -g yarn

variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - build

build:
  image: slauta93/electron-builder-win
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - yarn && yarn build
